server:
  port: ${PORT:7500}
  servlet:
    context-path: /orders

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:h2:file:~/orders;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: order
    password: order
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  logstash:
    server: logstash
    port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
