server:
  port: ${PORT:8762}

spring:
  application:
    name: api-gateway-service
  logstash:
    server: logstash
    port: 5000
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin:9411}/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: orders-service
          uri: lb://ORDERS-SERVICE
          predicates:
            - Path=/orders/**
        - id: products-service
          uri: lb://PRODUCTS-SERVICE
          predicates:
            - Path=/products/**
        - id: payments-service
            uri: lb://PAYMENTS-SERVICE
            predicates:
              - Path=/payments/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka